### ISSUE TITLE
Connect homepage features to BeatSaver curated playlist feed

### ISSUE THREAD

**Issue by helencarnate** [beastsaber/bsaber#11]
As a site browser, I want to view a reverse chronological (newest first) display of the four most recently curated playlists on BeatSaver so that I can see what has been newly featured.

Display should include a large version of the playlist cover image and the playlist name with an opacity gradient to make the name viewable with appropriate contrast. The map name should be a link directly to the BeatSaver page for that playlist. Example: https://beatsaver.com/playlists/30

**Reference:**
https://api.beatsaver.com/docs/index.html?url=./swagger.json#/OrderedMap%20%7B%20%22name%22%3A%20%22Playlists%22%20%7D/get_playlists_latest

**Comment by TimothyGillespie** [comment]
This has been addressed in #23.
