### ISSUE TITLE
Add ability to choose separate post/home page photo versus header photo on post

### ISSUE THREAD

**Issue by TheCzar1994** [beastsaber/bsaber#116]
Currently there is only one option for a post's photo that is used on the home page, at `/posts/page/1` listing, and at `/posts/(article-name-here)`. Because the title of the post is used over the image on the post's page, it's recommended to have no text in this image, however, on the home page and at `/posts/page/1` listing, it may be beneficial to have text on the image.

This task would be complete when the post creator can select a different image used for the post's page that is different from what is displayed on the home page and the `/posts/page/1` listing.

**Comment by TimothyGillespie** [comment]
This raises the following questions for me:

- Which should be used for the display of the image on the front page? I guess the backgroundable one?
- Which should be used in in the open graph data (which, for example, effects the preview image in the Discord embeds)?
- Which should be the default? I'd think the one that is by default backgroundable?

**Comment by TheCzar1994** [comment]
> Which should be used for the display of the image on the front page? I guess the backgroundable one?

Not entirely sure what you mean by the "backgoundable one" The image for the front page and the post listing pages would be the same, and then the one on the actual post/article page itself would in theory have no text (or the ability to be a different image).

> Which should be used in in the open graph data (which, for example, effects the preview image in the Discord embeds)?

I think we'd want the one that is used on the homepage and in the post listing pages.

> Which should be the default? I'd think the one that is by default backgroundable?

I agree with this, I think. I suppose in reality we'd want this to be an optional entry. So for example, the BeastSaber logo being used for announcement posts doesn't need a separate image for the post because it already has no text. On the other side, the BeastSaber Mapping Awards winners articles would look goofy on the home page and post listings page without text on them.

**Comment by TimothyGillespie** [comment]
With backgroundable I meant suitable to be a background, as it is kind of a background for the header. I did imply what it should be like with that and maybe that's a wrong description for it.

I'm not sure about the frontpage using the image with text, since we have text on it, since we have text on it already. So it could be noisy. For open graph, the embeds could be generally small so any text on their may be hard to read. But that should be fine.

**Comment by TheCzar1994** [comment]
This is old but I've decided against this. The primary use case would've been for Beasties where I use a specific image each time for the Winners post - but that's about the only time I'd ever use it. So it likely doesn't make sense to spend the time implementing this.
