### ISSUE TITLE
Redirect old song links to their respective BeatSaver pages

### ISSUE THREAD

**Issue by Pixelguymm** [beastsaber/bsaber#168]
BeastSaber used to have song pages with links such as: https://bsaber.com/songs/ff9
These links might still be used in some places like old articles and such. It shouldn't be too hard to redirect them to BeatSaver using the key in the URL. In this case: https://beatsaver.com/maps/ff9

**Comment by TimothyGillespie** [comment]
That makes a lot of sense. It's gonna be pretty difficult since we have a SSG'ed website.

Maybe that's something that can be configured in cloudflare, though.

**Comment by TheCzar1994** [comment]
Added through Cloudflare. This was a good idea!
