### ISSUE TITLE
Track page and post views

### ISSUE THREAD

**Issue by TimothyGillespie** [beastsaber/bsaber#94]
This is perhaps already implemented on the hosting side, but it would be great to know how many people have accessed a specific page or a post.

Nice to Have:

- display that information for posts publically

**Comment by helencarnate** [comment]
Here is the code snippet. Copy and paste it in the code of every page of your website, immediately after the <head> element
`
<script async src="https://www.googletagmanager.com/gtag/js?id=G-16Q4KP49MG"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-16Q4KP49MG');
</script>`
